### ISSUE TITLE
路徑問題

### ISSUE THREAD

**Issue by ucgJhe** [Inndy/super-simple-vulnerable-guestbook#1]
template 下的檔案沒有使用相對路徑，導致專案若不是在第一級目錄下，會造成 link 導向錯誤

**Comment by Inndy** [comment]
請問是哪個檔案哪行有問題呢？

**Comment by ucgJhe** [comment]
例如 home.php 及 new.php 都有 "action=/?mod=" 這個部份，如果我把整個專案放在非根目錄下，那麼連結會導向根目錄。

**Comment by Inndy** [comment]
事實上我是要讓他導向根目錄沒錯，請看 https://github.com/Inndy/super-simple-vulnerable-guestbook/blob/master/index.php#L23-36

**Comment by ucgJhe** [comment]
所以意思是 要完整的使用的話 請把專案放在**根目錄底下** 或是這樣別有用心呢？

**Comment by Inndy** [comment]
懂了，我沒有考慮到這個問題...有空來解一下！
